Sprache selector
Coderdojo-Schoeneweide/website-hugo pull request #118
Opened 2024-06-14 08:31 UTC by Abodx9

- Jetzt kann man eine der verfügbaren Sprachen auswählen 
- Deutsch ist die Hauptsprache 

![selector](https://github.com/Coderdojo-Schoeneweide/website-hugo/assets/70515761/4dddba32-ddba-47c3-89df-62d111ae8a91)

2024-06-18 20:03 UTC, Kaes3kuch3n requested changes
Es gibt leider einen Merge Conflict, weil der Branch alle Änderungen Deines anderen Branches enthält 😅 Kannst Du bitte einmal entweder die Commits für den Language Selector auf einen neuen Branch cherry-picken oder die Änderungen vom Master-Branch hier reinmergen?

2024-06-30 11:20 UTC, Kaes3kuch3n requested changes
Vielen Dank, funktioniert super 👍Ein paar kleine Anmerkungen habe ich an den entsprechenden Stellen hinterlassen, und allgemein habe ich auch noch zwei:
Könntest Du bitte die Klassen, die nicht verwendet werden, rausnehmen? Da die keinen direkten Zweck erfüllen, ist's ein bisschen sauberer, wenn sie nicht drinstehen (`abod-lang-2`, `hover:bg-slate-300`, `p-2`).
Und könntest Du den Sprach-Selektor noch ein bisschen mit SCSS gestalten, damit er sich besser in unser Design einfügt? Mein Vorschlag wäre, ihn zusammen mit dem Dark-Mode-Toggle in ein \<div\> zu packen und dem div dann `display: flex; justify-content: space-between` zu geben, damit die beiden jeweils oben links und oben rechts von unserem Logo sitzen :)

2024-06-30 11:20 UTC, Kaes3kuch3n commented on themes/coderdojoschoeneweide/layouts/_default/baseof.html
> +                    <img src="https://cdn-icons-png.flaticon.com/32/8281/8281549.png" alt="  ">
Wir können leider nicht einfach Bilder aus einer fremden Quelle einbinden, da wir das sonst in unserer Datenschutzerklärung berücksichtigen müssten. Könntest Du
 die Icons stattdessen runterladen und direkt als Dateien hinzufügen?
Außerdem müssen wir aufgrund der Lizenz, unter der die Icons stehen, auf die Quelle verweisen. Könntest Du entsprechende Verweise im Impressum ergänzen? Dort steht auch schon ein Verweis für unsere Font-Awesome-Icons :)

2024-06-30 11:20 UTC, Kaes3kuch3n commented on themes/coderdojoschoeneweide/layouts/_default/baseof.html
> +              {{/* <link rel="alternate" hreflang="{{ .Lang }}" href="{{ .Permalink }}" /> */}}
Bitte rausnehmen, falls das hier nicht mehr benötigt wird

2024-06-30 11:20 UTC, Kaes3kuch3n commented on themes/coderdojoschoeneweide/layouts/_default/baseof.html
> +    <div class="abod-lang-2">
Der ganze Block sollte wahrscheinlich in den \<header\>-Tag (weiter unten) anstatt in den \<head\>-Tag, oder? :D

2024-07-10 15:36 UTC, Abodx9 commented
## Jetzt werden die Icons lokal verwendet 
- config.toml -Konflikte gelöst
- neue Ordner-Flags für die Icons

2024-07-17 17:00 UTC, Kaes3kuch3n requested changes
Danke Dir :) Zwei Punkte, die ich im letzten Review angesprochen habe, sind aber noch offen. Könntest Du die beiden Punkte bitte nochmal angehen?

* Quellenverweis für die Icons: Könntest Du einen Verweis auf die Quelle der Icons im Impressum ergänzen? Dort steht auch schon ein Verweis für unsere Font-Awesome-Icons, den Du als Vorlage benutzen kannst :)
* HTML-Klassen und CSS:
  > Könntest Du bitte die Klassen, die nicht verwendet werden, rausnehmen? Da die keinen direkten Zweck erfüllen, ist's ein bisschen sauberer, wenn sie nicht drinstehen (abod-lang-2, hover:bg-slate-300, p-2).
Und könntest Du den Sprach-Selektor noch ein bisschen mit SCSS gestalten, damit er sich besser in unser Design einfügt? Mein Vorschlag wäre, ihn zusammen mit dem Dark-Mode-Toggle in ein \<div\> zu packen und dem div dann display: flex; justify-content: space-between zu geben, damit die beiden jeweils oben links und oben rechts von unserem Logo sitzen :)

2024-07-17 17:00 UTC, Kaes3kuch3n commented on themes/coderdojoschoeneweide/layouts/_default/baseof.html
> +        </label>
Könntest Du hier noch ein bisschen mit CSS nachbessern, damit es etwas schöner aussieht? Also sowas in der Art wie mein Vorschlag hier?

```suggestion
        <div style="display: flex; justify-content: space-between">
            <ul style="list-style: none; padding-left: 0; display:flex; gap: 1em;">
                {{ range .Translations }}
                {{ if eq .Lang "en" }}
                <li>
                    <a href="{{ .Permalink }}" style="display: flex; gap: 0.5em; align-items: center">
                        <img src="/images/flags/usa.png" alt="  ">
                        {{ " " | .RenderString }} English</a>
                </li>
                {{ else if eq .Lang "de" }}
                <li>
                    <a href="{{ .Permalink }}" style="display: flex; gap: 0.5em; align-items: center">
                        <img src="/images/flags/deutschland.png" alt=" ">
                        {{ " " | .RenderString }} Deutsch</a>
                </li>
                {{ else if eq .Lang "ar" }}
                <li>
                    <a href="{{ .Permalink }}" style="display: flex; gap: 0.5em; align-items: center">
                        <img src="/images/flags/jemen.png" alt=" ">
                        {{ " " | .RenderString }} العربية</a>
                </li>
                {{ end }}
                {{ end }}
            </ul>
            <label id="switch" class="switch">
                <input type="checkbox" id="slider"/>
                <span class="slider round"></span>
            </label>
        </div>
```

2024-07-24 16:22 UTC, Kaes3kuch3n approved these changes
Wundervoll, vielen Dank! Jetzt habe ich keine Anmerkungen mehr und denke, wir können es mergen :D

2024-07-24 16:22 UTC, merged