Datenschutz
Coderdojo-Schoeneweide/website-hugo pull request #83
Opened 2023-07-04 15:24 UTC by LiFaytheGoblin

2023-07-05 15:21 UTC, Kaes3kuch3n commented
Klingt sehr gut 👍 Der Abschnitt zu Google Fonts könnte theoretisch raus, und Cookies benutzen wir auch nicht, aber ist vielleicht auch nicht schlecht, es drin zu haben, falls wir das mal ändern sollten. Lieber ein bisschen zu viel als zu wenig

2023-07-05 15:39 UTC, Kaes3kuch3n requested changes
Die Datenschutzvereinbarung sieht gut aus, aber der Link dahin funktioniert leider noch nicht

2023-07-05 15:39 UTC, Kaes3kuch3n commented on themes/coderdojoschoeneweide/layouts/_default/baseof.html
> +      <p><a href="">Datenschutz</a></p>
Der Link ist leer, der funktioniert leider noch nicht 😅

2023-07-05 15:54 UTC, Kaes3kuch3n commented on content/datenschutz/_index.md
> +---
Theoretisch könnte diese Datei einfach `datenschutz.md` heißen und müsste dann nicht in einen Extra-Ordner. Aktuell erwartet Hugo nämlich aufgrund des Namensschemas (`_index.md`), dass es hier noch mehr Unterseiten gibt. Aber diese Seite ist ja die einzige zu Datenschutz, die wir haben.

2023-07-05 16:26 UTC, LiFaytheGoblin commented on config.toml
> +  weight = 4
Denke es wäre beides gut. Wenn für jetzt der Link erstmal über das HTML Template geht, aber eine neue Trello Karte erstellt wird um für das Menü auf die config umzusteigen.

2023-07-05 16:29 UTC, LiFaytheGoblin commented on themes/coderdojoschoeneweide/layouts/_default/baseof.html
> +      <p><a href="/datenschutz">Datenschutz</a></p>
ich denke entweder der link zum impressum sollte hier nach unten zum datenschutz, oder der datenschutz hoch zum impressum. die haben für mich das gleiche "level" irgendwie...

2023-07-05 16:30 UTC, LiFaytheGoblin commented on content/datenschutz/_index.md
> +<p>Diese Datenschutzerklärung gilt für alle von uns im Unternehmen verarbeiteten personenbezogenen Daten und für alle personenbezogenen Daten, die von uns beauftragte Firmen (Auftragsverarbeiter) ver
wir sind kein Unternehmen, sondern ein Verein

2023-07-05 16:33 UTC, LiFaytheGoblin commented on content/datenschutz/_index.md
> +Linda Fernsel<br />
Bitte meine Daten hier nicht im Klartext reintun. Ich will nicht dass sie von crawlern gefunden werden. stattdessen mit rot13 verschlüsselung wie beim impressum angeben. kannst die infos sonst auch erstmal rauslassen und ich baue das mit nem commit ein.

2023-07-19 15:26 UTC, LiFaytheGoblin commented
Todo für mich: Am Ende nochmal prüfen ob abgedeckt ist, was mit den Daten die via Pretix gesammelt werden, passiert.

2023-08-02 14:37 UTC, Kaes3kuch3n approved these changes

2023-08-02 14:38 UTC, merged